name: ESPHome
slug: esphome
type: docker
description: ESPHome is a system to control your microcontrollers by simple yet powerful
  configuration files and control them remotely through Home Automation systems.
tagline: Home Automation systems
category: home-automation
developer:
  name: kd9lsv
  website: ''
icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/icon.png
screenshots:
- https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/screenshot-1.png
- https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/ESPHome/screenshot-2.png
arch:
- amd64
- arm64
- arm
resources:
  min_ram: 512
  profiles:
    light:
      ram: 256
      cpu: 0.5
    standard:
      ram: 512
      cpu: 1
    performance:
      ram: 1024
      cpu: 2
ports:
- container: 6052
  host: 6052
  description: Service port 6052
  protocol: tcp
volumes:
- container: /config
  description: App configuration
  required: true
env:
- name: ESPHOME_DASHBOARD_USE_PING
  default: 'false'
  description: ESPHOME_DASHBOARD_USE_PING environment variable
  advanced: true
- name: TZ
  default: $TZ
  description: TZ environment variable
  advanced: true
web_ui:
  port: 6052
  path: /
