name: Grafana
slug: grafana
type: docker
description: 'Grafana open source is open source visualization and analytics software.Visualizations:
  Fast and flexible client side graphs with a multitude of options. Panel plugins
  offer many different ways to visualize metrics and logs. Dynamic Dashboards: Create
  dynamic & reusable dashboards with template variables that appear as dropdowns at
  the top of the dashboard. Explore Metrics: Explore your data through ad-hoc queries
  and dynamic drilldown. Split view and compare different time ranges, queries and
  data sources side by side. Explore Logs: Experience the magic of switching from
  metrics to logs with preserved label filters. Quickly search through all your logs
  or streaming them live. Alerting: Visually define alert rules for your most important
  metrics. Grafana will continuously evaluate and send notifications to systems like
  Slack, PagerDuty, VictorOps, OpsGenie. Mixed Data Sources: Mix different data sources
  in the same graph! You can specify a data source on a per-query basis. This works
  for even custom datasources.'
tagline: Grafana is a complete observability stack that allows you to monitor and
  analyze metrics, logs and traces. It allows you to query, visualize, alert on and
  understand your data no matter where it is stored.
category: network-and-dns
developer:
  name: grafana
  website: ''
icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/icon.png
screenshots:
- https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/screenshot-1.png
- https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/screenshot-2.png
- https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Grafana/screenshot-3.png
arch:
- amd64
- arm64
resources:
  min_ram: 512
  profiles:
    light:
      ram: 256
      cpu: 0.5
    standard:
      ram: 512
      cpu: 1
    performance:
      ram: 1024
      cpu: 2
ports:
- container: 3000
  host: 3003
  description: Service port 3000
  protocol: tcp
volumes:
- container: /var/lib/grafana
  description: Mount for /var/lib/grafana
  required: false
env: []
web_ui:
  port: 3003
  path: /
